name = "cf-r2-webdav"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[vars]
USERNAME = "zhangyj"
PASSWORD = "19910420"
BUCKET_NAME = "zotero"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "zotero"
